ALTER TABLE deployments DROP COLUMN IF EXISTS org_id;
ALTER TABLE devices DROP COLUMN IF EXISTS org_id;
ALTER TABLE models DROP COLUMN IF EXISTS org_id;
ALTER TABLE fleets DROP COLUMN IF EXISTS org_id;
ALTER TABLE users DROP COLUMN IF EXISTS org_id;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS organizations;
